name: Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: "Team: ${{ matrix.team }}"
    uses: osinfra-io/github-opentofu-gcp-called-workflows/.github/workflows/plan-and-apply.yml@e3c59e43f2458550c7f13b6369fb6978b6f42c6e # v0.2.9
    if: github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        team:
          - pt-logos
          # - pt-corpus
          # - pt-pneuma
          # - st-ethos
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Production: Main"
      service_account: pt-logos-github@pt-corpus-tf16-prod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/pt-corpus-tf16-prod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=teams/${{ matrix.team }}.tfvars
      opentofu_state_bucket: pt-logos-state-prod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: "${{ matrix.team }}-main-production"
      workload_identity_provider: projects/557265520053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
